version: "3.7"
services:
  
  app-build:
    build: 
      context: .
      dockerfile: Dockerfile.dev.build
      args: 
        MAVEN_TAG: 3.8.3-openjdk-11 #Exemplo
    restart: on-failure
    volumes: 
      - ./backend-build.dev.sh:/usr/src/app/backend-build.dev.sh
      - ./my-app:/usr/src/app
      - local-repo:/usr/share/maven/ref/repository
      - deploy:/usr/src/app/target/
    entrypoint: sh -c "./backend-build.dev.sh"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        JAVA_TAG: 11-jdk-slim-buster #Exemplo
    ports:
      - "8080:8080" #Exemplo
    volumes:
      - deploy:/app
    depends_on: 
        - app-build
    command: sh -c "java -jar my-app-1.0-SNAPSHOT.jar" #Exemplo

volumes:
  local-repo:
  deploy:
